FROM ubuntu:18.04
RUN apt-get update \
 && apt-get install --no-install-recommends -y gcc build-essential
RUN mkdir -p /opt/darknet
RUN mkdir -p /opt/bin
COPY . /opt/darknet
WORKDIR /opt/darknet
RUN mkdir build && cd build && cmake -DENABLE_ZED_CAMERA=off -DENABLE_CUDNN_HALF=off -DENABLE_OPENCV=off .. && make -j8 && cp darknet /opt/bin
